#!/bin/bash
# 建立並赋予 jubo_app 讀寫 TABLES, SEQUENCES, FUNCTIONS 的權限
set -e

cd /docker-entrypoint-initdb.d
psql -v ON_ERROR_STOP=1 -U postgres <<-EOSQL
CREATE USER $POSTGRES_INITDB_APP_USERNAME with encrypted password '$POSTGRES_INITDB_APP_PASSWORD';
EOSQL

# medical
psql -v ON_ERROR_STOP=1 -U postgres medical <<-EOSQL
ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES
TO $POSTGRES_INITDB_APP_USERNAME;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT ALL ON SEQUENCES
TO $POSTGRES_INITDB_APP_USERNAME;
EOSQL
